### ISSUE TITLE
Live Token Stats

### ISSUE THREAD

**Issue by DonDuala** [Dual-Finance/status#140]
Create a tab within status or separate page that tracks all DUAL token information

Example from May 5th 2023
DUAL Stats:
Staking Options    122,909,729
DAO Treasury    853,131,367
Non-Circulating    976,041,096
Total Supply    1,000,000,000
Total Circulating    23,958,904
Unique Holders: 119
DAO Voting Deposits: 
DAO Voting Memebers: 42
Price    $0.02647
Mkt Cap    $634,192
DAO Value    $658,265
Break Even    $0.02747

For a reference, holder page has most of the data embedded: https://solscan.io/token/DUALa4FC2yREwZ59PHeu1un4wis36vHRv5hWVBmzykCJ#holders

DAO Members data: https://app.realms.today/dao/dual%20dao/members

Spreadsheet manually tracking data: https://docs.google.com/spreadsheets/d/1AwAoqyXEmJtUTAqPgm1_4sTx-H5-UzMwcEZMcN-hm00/edit#gid=985382977

This page could also hold the Option Strike Map: https://github.com/Dual-Finance/status/issues/124
![image](https://github.com/Dual-Finance/status/assets/107803907/b4c23424-7260-4d85-a46b-a9543df5eb11)

Related Issue: https://github.com/Dual-Finance/status/issues/116

**Comment by siirtecirlioglu** [comment]
Im happy to pick this up next week 💪

**Comment by FiyinOdebunmi** [comment]
hey @DonDuala , i will like to work on this issue. Can you assign to me pls?

**Comment by FiyinOdebunmi** [comment]
is there a design system for Dual Finance i could use? @DonDuala
