### ISSUE TITLE
Discord Bot to Alert of Staking Transactions

### ISSUE THREAD

**Issue by DonDuala** [Dual-Finance/status#63]
The Zapier bot will run out of tasks soon. We should just make a discord webhook that you can input addresses to track transactions to/from

**Comment by brittcyr** [comment]
Would be non trivial to run our own geyser to do this. Although eventually we should have one for other reasons. Might be best to use a service like helius for this
https://twitter.com/heliuslabs/status/1574800502344323078

**Comment by DonDuala** [comment]
Good call Helius seems like the way to do this

**Comment by DonDuala** [comment]
Done via helius
