### ISSUE TITLE
Mobile support for SO & GSO tabs

### ISSUE THREAD

**Issue by DonDuala** [Dual-Finance/status#85]

**Comment by DonDuala** [comment]
![Screenshot_20230126-114827_Brave](https://user-images.githubusercontent.com/107803907/214897203-b18eb90c-7d9e-456d-a8b0-2f02e90ea769.jpg)
In desktop mode they also dont show on mobile?

**Comment by WaggMe** [comment]
So:
- On a zoomed/mobile screen, the second menu switches from 'network' to a redundant 'tab' dropdown

![image](https://user-images.githubusercontent.com/96327301/229887509-86388167-4f27-47b2-b73d-4e3c6fbf8c50.png)
